### PR TITLE
Cell Scalar-tensor:NSNR

### PR DESCRIPTION
**Pull request by hosilva**
Please check if update was made correctly.

### CODE REVIEW

**Comment by duetosymmetry** [comment]
Please include all refs from this table cell (line 284 of `summarytables.tex`) rather than just one.

Please provide a more descriptive commit message.

**Comment by hosilva** [comment]
I see that now my second commit appears in the PR log. Nice.

**Review by duetosymmetry — CHANGES_REQUESTED** [review]
1. There was no checkmark in the original table ;)
2. ~~~Please squash commits down so there is only one commit~~~ Actually, it turns out that I can squash the commits at the time when I accept the PR, so this isn't too important.

**Comment by hosilva** [comment]
Ooops, removed the checkmark :)

**Review by duetosymmetry — APPROVED** [review]

**Comment by duetosymmetry** [comment]
Squashed three commits down to one and rebased in bea5d9ec11924b34820deb1a05d59123aa5218df

**Pull request closed without merging**
